[package]
name = "ramdl"
version = "0.1.0"
edition = "2021"

[dependencies]
fancy-regex = "0.14.0"
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version = "1.0.215", features = ["serde_derive"] }
serde_json = "1.0.132"
thiserror = "2.0.3"
tokio = { version = "1.41.1", features = ["full"] }
